# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-01 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211201_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 1, 17, 32, 31, 408793), verbose_name='Опубликован'),
        ),
    ]
